### ISSUE TITLE
Running tests failed.

### ISSUE THREAD

**Issue by ewan1983** [ShaneFlandermeyer/MOTpy#1]
I run a test
`python test_kalman.py`
output error:
> File "...miniconda3\Lib\site-packages\motpy\models\measurement\linear.py", line 14, in LinearMeasurementModel
>     seed: int = np.random.randint(0, 2**32-1),
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "numpy\\random\\mtrand.pyx", line 780, in numpy.random.mtrand.RandomState.randint
>   File "numpy\\random\\_bounded_integers.pyx", line 1423, in numpy.random._bounded_integers._rand_int32
> ValueError: high is out of bounds for int32

Looks like on windows np.int_ or int as dtype uses the C type long. The long type is just 4bytes on Windows (even 64 bit):
https://msdn.microsoft.com/en-us/library/9c3yd98k.aspx

So, I specify dtype to solve the immediate problem:
`seed: int = np.random.randint(0, 2**32-1, dtype=np.uint32),` 

Now the result is:

python run_all.py
================================================= test session starts =================================================
platform win32 -- Python 3.11.4, pytest-8.2.2, pluggy-1.5.0
rootdir: C:\Reference\MOTpy-main
plugins: anyio-3.5.0
collected 13 items

test_bernoulli.py ...FF                                                                                          [ 38%]
test_kalman.py ..                                                                                                [ 53%]
test_momb.py .                                                                                                   [ 61%]
test_poisson.py FF                                                                                               [ 76%]
test_tomb.py .                                                                                                   [ 84%]
test_ukf.py ..                                                                                                   [100%]

====================================================== FAILURES =======================================================
_____________________________________________ test_undetected_likelihood ______________________________________________

    def test_undetected_likelihood():
      pd = 0.8147
      r = 0.9058
      bern = Bernoulli(r=r,
                       state=GaussianState(mean=np.ones(4), covar=np.eye(4)))
>     l = bern.log_likelihood(pd=pd, measurements=None)
E     AttributeError: 'Bernoulli' object has no attribute 'log_likelihood'

test_bernoulli.py:120: AttributeError
______________________________________________ test_detected_likelihood _______________________________________________

    def test_detected_likelihood():
      pd = 0.8147
      bern = Bernoulli(r=0.9058,
                       state=GaussianState(mean=np.ones(4), covar=np.eye(4)))
      measurement_model = LinearMeasurementModel(sigma=1)
      kf = KalmanFilter(transition_model=None, measurement_model=measurement_model)

      measurements = np.ones(2)
>     l = bern.log_likelihood(pd=pd, measurements=measurements, state_estimator=kf)
E     AttributeError: 'Bernoulli' object has no attribute 'log_likelihood'

test_bernoulli.py:132: AttributeError
____________________________________________________ test_predict _____________________________________________________

    def test_predict():
      T = 1
      ps = 0.2785
      ekf = ExtendedKalmanFilter(
          transition_model=ConstantTurnModel(sigma_v=1, sigma_w=np.pi/180),
          measurement_model=None,
      )
      # Weights should be LOG weights
      birth_weights = np.array([-0.2049]*4)
      birth_states = [
          GaussianState(mean=np.array([0.9058, 0.1270, 0.9134, 0.6324, 0.0975]),
                        covar=np.diag([1, 1, 1, 1*np.pi/90, 1*np.pi/90])**2)
          for _ in range(4)
      ]

      ppp = Poisson(
          birth_weights=birth_weights, birth_states=birth_states)
      # Use custom states and weights for testing
      ppp.states = []
      ppp.states.append(GaussianState(mean=np.array([0, 0, 5, 0, np.pi/180]),
                                      covar=np.eye(5)))
      ppp.states.append(GaussianState(mean=np.array([20, 20, -20, 0, np.pi/90]),
                                      covar=np.eye(5)))
      ppp.states.append(GaussianState(mean=np.array([-20, 10, -10, 0, np.pi/360]),
                                      covar=np.eye(5)))
      ppp.weights = np.array([-0.6035, -0.0434, -0.0357])

      ppp = ppp.predict(state_estimator=ekf, ps=ps, dt=T)

      expected_weights = np.array(
          [-1.8819, -1.3218, -1.3141, -0.2049, -0.2049, -0.2049, -0.2049,])
      expected_mean = np.array([5, 0, 5, 0.0175, 0.0175])
      expected_covar = np.array([[2, 0, 1, 0, 0],
                                 [0, 26, 0, 5, 0.],
                                 [1,  0, 2, 0, 0.],
                                 [0,  5, 0, 2, 1.],
                                 [0,  0, 0, 1, 1.00030462]])
>     assert np.allclose(ppp.weights, expected_weights, atol=1e-4)
E     assert False
E      +  where False = <function allclose at 0x000002971722D7F0>(array([-0.16807475, -0.0120869 , -0.00994245, -0.2049    , -0.2049    ,\n       -0.2049    , -0.2049    ]), array([-1.8819, -1.3218, -1.3141, -0.2049, -0.2049, -0.2049, -0.2049]), atol=0.0001)
E      +    where <function allclose at 0x000002971722D7F0> = np.allclose
E      +    and   array([-0.16807475, -0.0120869 , -0.00994245, -0.2049    , -0.2049    ,\n       -0.2049    , -0.2049    ]) = PoissonPointProcess(log_weights=[-0.16807475000000002, -0.012086900000000001, -0.009942450000000002, -0.2049, -0.2049,...         0.         0.00121847 0.        ]\n [0.         0.         0.         0.         0.00121847]])\n      meta={})]).weights

test_poisson.py:108: AssertionError
________________________________________________ test_detected_update _________________________________________________

    def test_detected_update():
      pd = 0.8147
      clutter_intensity = 0.0091
      ekf = ExtendedKalmanFilter(
          transition_model=None,
          measurement_model=RangeBearingModel(
              sigma_r=5, sigma_b=np.pi/180, s=np.array([300, 400]))
      )

      ppp = Poisson(birth_weights=None, birth_states=None)
      ppp.states.append(GaussianState(mean=np.array([0, 0, 5, 0, np.pi/180]),
                                      covar=np.eye(5)))
      ppp.states.append(GaussianState(mean=np.array([20, 20, -20, 0, np.pi/90]),
                                      covar=np.eye(5)))
      ppp.states.append(GaussianState(mean=np.array([-20, 10, -10, 0, np.pi/360]),
                                      covar=np.eye(5)))
      ppp.weights = np.array([-2.0637, -0.0906, -0.4583])

      in_gate = np.array([True, False, True])
      z = ekf.measurement_model(ppp.states[0].mean)
>     bern, total_log_likelihood = ppp.update(
          measurement=z, in_gate=in_gate, state_estimator=ekf,
          pd=pd, clutter_intensity=clutter_intensity)
E     TypeError: Poisson.update() missing 1 required positional argument: 'likelihoods'

test_poisson.py:134: TypeError
=============================================== short test summary info ===============================================
FAILED test_bernoulli.py::test_undetected_likelihood - AttributeError: 'Bernoulli' object has no attribute 'log_likelihood'
FAILED test_bernoulli.py::test_detected_likelihood - AttributeError: 'Bernoulli' object has no attribute 'log_likelihood'
FAILED test_poisson.py::test_predict - assert False
FAILED test_poisson.py::test_detected_update - TypeError: Poisson.update() missing 1 required positional argument: 'likelihoods'
============================================ 4 failed, 9 passed in 10.68s =============================================

**Comment by ShaneFlandermeyer** [comment]
I would recommend using the develop branch. Although the MOMB filter is currently broken there (and some tests fail), the Kalman filter (and UKF), measurement/transition models, and TOMB filter work. 

I hope to pretty everything up at some point, but that time has not yet come...

Let me know if you have other related issues. Otherwise, closing this one.
